# Generated by Django 3.1 on 2020-08-30 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='type',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='post_type',
            field=models.ManyToManyField(to='blog.Type'),
        ),
    ]
